### ISSUE TITLE
Do you mind if I write a request to be added to F-Droid?

### ISSUE THREAD

**Issue by Artem13327** [d4rken-org/permission-pilot#148]

**Comment by d4rken** [comment]
I don't mind, see also https://apt.izzysoft.de/packages/eu.darken.myperm/

**Comment by d4rken** [comment]
```yaml
AuthorName: Matthias Urhahn
AuthorEmail: darken@darken.eu
AuthorWebSite: https://darken.eu
Donate: https://github.com/sponsors/d4rken

SourceCode: https://github.com/d4rken-org/permission-pilot
IssueTracker: https://github.com/d4rken-org/permission-pilot/issues
Changelog: https://github.com/d4rken-org/permission-pilot/releases
```
